<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2015] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2015 Cart2Quote B.V. (http://www.cart2quote.com)
 * @license     http://www.cart2quote.com/ordering-licenses
 */
?>
<?php if (!Mage::helper('qquoteadv')->isEnabled()) return ''; ?>
<?php
$_product = $this->getProduct();
$hideCartButton = false;
$hideQuoteButton = Mage::helper('qquoteadv')->hideQuoteButton($_product);
if (Mage::getConfig()->getModuleConfig('Ophirah_Not2Order')->is('active', 'true') && $_product->getData('quotemode_conditions') > 0) {
    $hideCartButton = Mage::helper('not2order')->autoHideCartButton($hideQuoteButton);
}

$url = $this->helper('qquoteadv/catalog_product_data')->getUrlAdd2Qquoteadv($_product);
$isAjax = Mage::getStoreConfig('qquoteadv_quote_frontend/catalog/ajax_add');
$actionQuote = "addQuote('" . $url . "', $isAjax );";

// Quick Quote Data
if (Mage::getStoreConfig('qquoteadv_advanced_settings/quick_quote/quick_quote_mode') == "1") {
    // Storing current action in session
    // Ajax needs to be disabled
    Mage::getSingleton('customer/session')->setData('quickQuoteUrl', "addQuote('" . $url . "', 0 );");
    $actionQuote = "$('quickQuoteWrapper').show()";
}
?>

<div class="add-to-cart">
    <?php if ($_product->getData('allowed_to_quotemode') == 1 && $hideQuoteButton === false): ?>
        <?php if (!$_product->isGrouped() && (!$_product->isSaleable() || $hideCartButton === true)): ?>
            <div class="qty-wrapper">
                <label for="qty"><?php echo Mage::helper('catalog')->__('Qty:'); ?></label>
                <input type="text" pattern="\d*" name="qty" id="qty" maxlength="12"
                       value="<?php echo max($this->getProductDefaultQty() * 1, 1) ?>"
                       title="<?php echo Mage::helper('catalog')->__('Qty') ?>" class="input-text qty"/>
            </div>
        <?php endif; ?>
        <div class="add-to-cart-buttons">
            <button type="button" title="<?php echo Mage::helper('qquoteadv')->__("Add to Quote"); ?>"
                    class="button btn-cart btn-quote" onclick="<?php echo $actionQuote; ?>">
                <span><span><?php echo Mage::helper('qquoteadv')->__("Add to Quote"); ?></span></span></button>
        </div>
    <?php endif; ?>
</div>