<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2015] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2015 Cart2Quote B.V. (http://www.cart2quote.com)
 * @license     http://www.cart2quote.com/ordering-licenses
 */
?>
<?php
// get billing email
$billingEmail = $this->getValue('email', 'billing');

// get required data
$requireShipping = (Mage::getStoreConfig('qquoteadv_quote_form_builder/options/require_shipping')) ? true : false;
$requireBilling = (Mage::getStoreConfig('qquoteadv_quote_form_builder/options/require_billing')) ? true : false;
$requireExtraOptions = (Mage::getStoreConfig('qquoteadv_quote_form_builder/options/require_delivery_options')) ? true : false;

// get form builder settings
$formOptionAccountTelephone = Mage::getStoreConfig('qquoteadv_quote_form_builder/account_details/telephone');
$formOptionAccountCompany   = Mage::getStoreConfig('qquoteadv_quote_form_builder/account_details/company');
$formOptionAccountVattaxid  = Mage::getStoreConfig('qquoteadv_quote_form_builder/account_details/vattaxid');
$formOptionAddressState     = Mage::getStoreConfig('qquoteadv_quote_form_builder/address_details/state');

// gets data from session and the second parameter TRUE removes it
$shippingRatesRequested = Mage::getSingleton('customer/session')->getData('quoteRateRequest', true);

// get customer from session
$customer = $this->getCustomerSession()->getCustomer();

//get persisent client request
$quoteId = $this->getCustomerSession()->getQuoteadvId();
if ($quoteCustomer = Mage::getModel('qquoteadv/qqadvcustomer')->load($quoteId)) {
    $clientRequest = $quoteCustomer->getClientRequest();
    if (!isset($clientRequest) || empty($clientRequest)) {
        $clientRequest = $customer->getData('client_request');
    }
} else {
    $clientRequest = $customer->getData('client_request');
}

// Add customer information after shipping estimate request
if ($quoteCustomer = Mage::getSingleton('customer/session')->getData('quoteCustomer')) {
    $customer->addData($quoteCustomer->getData());
}
?>

<div class="qquote-client-collaterals">
<div class="quote-forms">
<div class="client-data box">
    <h2><?php echo Mage::helper('qquoteadv')->__('Remarks') ?></h2>
    <?php echo $this->__('Do you have a general remark with your quote request?') ?>
    <br/>
    <textarea name="customer[client_request]" id="customer:client_request" cols="10" rows="5" class="input-text"><?php echo $clientRequest; ?></textarea>
    <?php if ($this->isCustomerLoggedIn() && !empty($billingEmail)): ?>
        <fieldset>
            <div class="inline-checkbox">
                <?php if ($requireExtraOptions === false): ?>
                    <input id="default_billing_shipping_address_checkbox" type="checkbox" name="billing_address" value="use_default_billing" checked="checked">
                <?php else: ?>
                    <input type="checkbox" name="billing_address" value="use_default_billing" checked="checked">
                <?php endif; ?>

                <label for="customer:use_default_billing"><?php echo $this->__('Use Default Billing and Shipping Address') ?></label>
            </div>
        </fieldset>
    <?php endif; ?>
</div>
<div <?php echo $this->isCustomerLoggedIn() && !empty($billingEmail) ? 'id="billing-new-address-form"' : 'class="input-box"' ?>>
    <div id="accountDiv">
        <?php $email = $customer->getEmail() ? $customer->getEmail() : $this->getCustomerEmail() ?>
        <table id="qquote-tbl-address" cellspacing='6' cellpadding='3'>
            <tr>
                <td class="left">
                    <label>
                        <?php echo Mage::helper('sales')->__('Email Address') ?> <span class="required"></span><br/>
                    </label>
                    <input <?php if (!empty($email)): ?>readonly="readonly"<?php endif; ?> type='text'
                           value="<?php echo $email; ?>"
                           name='customer[email]' id='customer:email'
                           class="validate-email required-entry input-text"/><span id="please-wait"
                                                                                   style="display:none;"><img
                            alt="<?php echo $this->__('Checking..') ?>"
                            src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>"/></span>

                    <div style="display:none;" id="email_message">&nbsp;</div>
                </td>
                <td class="p5">
                </td>
            </tr>
            <tr>
                <td class="left">
                    <label>
                        <?php echo Mage::helper('sales')->__('First Name') ?> <span class="required"></span><br/>
                    </label>
                    <input type='text' value="<?php echo $customer->getData('firstname'); ?>"
                           name='customer[firstname]' id='customer:firstname' class="required-entry input-text"/>
                </td>
                <td class="p5">
                    <label>
                        <?php echo Mage::helper('sales')->__('Last Name') ?> <span class="required"></span><br/>
                    </label>
                    <input type='text' value="<?php echo $customer->getData('lastname'); ?>"
                           name='customer[lastname]' id='customer:lastname' class="required-entry input-text"/>
                </td>

            </tr>
            <tr>
                <td class="left">
                    <label>
                        <?php
                        if($formOptionAccountTelephone != 0){
                            echo Mage::helper('sales')->__('Telephone');
                            if($formOptionAccountTelephone == 2){
                                echo '<span class="required"></span>';
                            }
                        }
                        ?><br/>
                    </label>
                    <input type='<?php if($formOptionAccountTelephone == 0){ echo 'hidden'; } else {echo 'text'; } ?>'
                           value="<?php echo $this->getValue('telephone', 'billing') ?>"
                           name='customer[telephone]' id='customer:telephone'
                           class="<?php if($formOptionAccountTelephone == 2){ echo 'required-entry'; } ?> input-text"/>
                </td>
                <td class="p5">
                    <label>
                        <?php
                        if($formOptionAccountCompany != 0){
                            echo Mage::helper('sales')->__('Company');
                            if($formOptionAccountCompany == 2){
                                echo '<span class="required"></span>';
                            }
                        }
                        ?><br/>
                    </label>
                    <input type='<?php if($formOptionAccountCompany == 0){ echo 'hidden'; } else {echo 'text'; } ?>'
                           value="<?php echo $this->getValue('company', 'billing') ?>"
                           name='customer[company]' id='customer:company'
                           class="<?php if($formOptionAccountCompany == 2){ echo 'required-entry'; } ?> input-text"/>
                </td>
            </tr>
            <tr>
                <td class="left">
                    <label>
                        <?php
                        if($formOptionAccountVattaxid != 0){
                            echo Mage::helper('customer')->__('VAT Number');
                            if($formOptionAccountVattaxid == 2){
                                echo '<span class="required"></span>';
                            }
                        }
                        ?><br/>
                    </label>
                    <input type='<?php if($formOptionAccountVattaxid == 0){ echo 'hidden'; } else {echo 'text'; } ?>'
                           value="<?php echo $this->getValue('vat_id', 'billing') ?>"
                           name='customer[vat_id]' id='customer:vat_id'
                           class="<?php if($formOptionAccountVattaxid == 2){ echo 'required-entry'; } ?> input-text"/>
                </td>
                <td class="p5">
                </td>
            </tr>
            <?php echo $this->getChildHtml('qquote.extrafields'); ?>
            <tr>
                <td class="left"></td>
                <td class="p5"><p class="required"
                                  style="float:right; "> <?php echo Mage::helper('sales')->__('* Required Fields') ?></p>
                </td>
            </tr>
            <?php
            // Adding extra option fields
            // pass Option Types as argument
            // to getExtraoptionsForm()
            $extraOptions = Mage::getModel('qquoteadv/extraoptions')->getExtraoptionsForm();

            if ($extraOptions != NULL):
                foreach ($extraOptions as $option):
                    $pos1 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS1;
                    $pos2 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS2;
                    ?>
                    <tr>
                        <td class="left">
                            <?php
                            if ($option[$pos1] != NULL):
                                $required = (isset($option[$pos1]['required'])) ? $option[$pos1]['required'] : false;
                                echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos1], $required);
                            endif; ?>
                        </td>
                        <td class="p5">
                            <?php
                            if ($option[$pos2] != NULL):
                                $required = (isset($option[$pos2]['required'])) ? $option[$pos2]['required'] : false;
                                echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos2], $required);
                            endif;?>
                        </td>
                    </tr>
                <?php
                endforeach;
            endif;
            ?>
        </table>
    </div>



    <?php if (!$this->isCustomerLoggedIn()): ?>
        <?php
        $chkShipHidden = Mage::getStoreConfig('qquoteadv_quote_form_builder/options/hide_shipping_quote');
        if ($chkShipHidden){
            $chkShipType = 'hidden';
        } else {
            $chkShipType = 'checkbox';
        }
        ?>
        <div class="inline-checkbox">
            <?php if ($requireShipping === false && $requireBilling === false): ?>
                <input id="chkShip" type="<?php echo $chkShipType; ?>" <?php if ($shippingRatesRequested) {
                    echo 'checked="checked"';
                } ?> >
                <label for="chkShip"><?php if(!$chkShipHidden){echo $this->__('Request a shipping quote');} ?></label>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
</div>

<div <?php if ($this->isCustomerLoggedIn() && !empty($billingEmail)) {
    echo 'id="qquoteadv_shipping_box"';
} ?> class="qquote-cart-collaterals">

<div class="quote-forms">
<div id="shipDiv">
    <h2><?php echo $this->__('Shipping details') ?></h2>

    <p><?php echo $this->__("Enter your destination to receive a shipping quotation. Unless otherwise specified, standard shipping is quoted.") ?></p>


    <table id="qquote-tbl-shipping" cellspacing='3' cellpadding='3' border="0" width="100%">
        <?php
            echo $this->getMultipleLineAddress('shipping');
        ?>
        <tr>
            <td class="left">
                <?php echo Mage::helper('sales')->__('Zip/Postal Code') ?> <span class="required"></span><br/>
                <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type='text'
                       value="<?php echo $this->getValue('postcode', 'shipping'); ?>"
                       name='customer[shipping_postcode]'
                       id='customer:shipping_postcode' class="required-entry input-text w224"/>
            </td>
            <td class="p5">
                <?php echo Mage::helper('sales')->__('City') ?> <span class="required"></span><br/>
                <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type='text'
                       value="<?php echo $this->getValue('city', 'shipping'); ?>" name='customer[shipping_city]'
                       id='customer:shipping_city' class="required-entry input-text w224"/>
            </td>

        </tr>
        <tr>
            <td class="left">
                <?php
                $ratesList = array();
                if (count(Mage::getSingleton('customer/session')->getData('quoteRatesList')) > 0) {
                    $ratesList = Mage::getSingleton('customer/session')->getData('quoteRatesList');
                    echo $this->__('Shipping Estimate') . '<br />';
                    echo "<select id='shipping_method' name='customer[shipping_method]'>";
                    foreach ($ratesList as $rate) {
                        echo '<option value="' . $rate['value'] . '">' . $rate['option'] . '</option>';
                    }
                    echo "</select>";

                    Mage::getSingleton('customer/session')->unsetData('quoteRatesList', '');
                    Mage::getSingleton('customer/session')->unsetData('quotecustomer', '');
                }
                ?>
            </td>
            <td class="p5"></td>
        </tr>
        <?php //$countryCode = $this->getValue('country', 'billing'); ?>
        <?php //if (empty($countryCode)) { $countryCode = null; } ?>

        <tr>
            <td class="left">
                <?php echo Mage::helper('sales')->__('Country') ?> <span class="required"></span><br/>
                <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getValue('country_id', 'shipping'), 'customer[shipping_country_id]', 'shipping_country', $this->__('Country')) ?>
            </td>
            <td class="p5">
                <?php if($formOptionAddressState > 0){ ?>
                    <?php
                    echo Mage::helper('sales')->__('State/Province');
                    if($formOptionAddressState == 2){
                        echo '<span class="required"></span>';
                    }
                    ?><br/>
                    <select name='customer[shipping_region_id]' id='shipping_region_id'
                            title="<?php echo Mage::helper('sales')->__('State/Province') ?>"
                            class="<?php if($formOptionAddressState == 2){ echo 'required-entry'; } ?> validate-select w224"
                            style="display:none;">
                        <option value=""><?php echo $this->getValue('region_id', 'shipping'); ?></option>
                    </select>
                    <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type="text"
                           name='customer[shipping_region]'
                           id='shipping_region' value="<?php echo $this->getValue('region', 'shipping'); ?>"
                           title="<?php echo Mage::helper('sales')->__('State/Province') ?>"
                           class="<?php if($formOptionAddressState == 2){ echo 'required-entry'; } ?> input-text w224"/>
                <?php } else { ?>
                    <input name='customer[shipping_region_id]' id='shipping_region_id'
                           title="<?php echo Mage::helper('sales')->__('State/Province') ?>" type="hidden" />
                <?php } ?>
            </td>

        </tr>
        <?php
        // Adding extra option fields
        // pass Option Types as argument
        // to getExtraoptionsForm()
        $extraOptions = Mage::getModel('qquoteadv/extraoptions')->getExtraoptionsForm(array());

        if ($extraOptions != NULL):
            foreach ($extraOptions as $option):
                $pos1 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS1;
                $pos2 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS2;
                ?>
                <tr>
                    <td class="left">
                        <?php
                        if ($option[$pos1] != NULL):
                            $required = (isset($option[$pos1]['required'])) ? $option[$pos1]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos1], $required);
                        endif; ?>
                    </td>
                    <td class="p5">
                        <?php
                        if ($option[$pos2] != NULL):
                            $required = (isset($option[$pos2]['required'])) ? $option[$pos2]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos2], $required);
                        endif;?>
                    </td>
                </tr>
            <?php
            endforeach;
        endif;
        ?>
    </table>
    <div id="addressCheckbox">
        <?php if (!$requireBilling): ?>
            <div class="inline-checkbox">
                <input id="chkBill" type="checkbox" checked="checked" name="customer[billIsShip]">
                <label><?php echo $this->__('Billing Address is same as Shipping Address'); ?></label>
            </div>
        <?php elseif (!$requireBilling && $requireShipping): ?>
            <div class="inline-checkbox">
                <input id="chkBill" type="checkbox" checked="checked" name="customer[shipIsBill]">
                <label><?php echo $this->__('Shipping Address is same as Billing Address'); ?></label>
            </div>
        <?php endif; ?>
        <?php // BETA FEATURE
        //if (Mage::helper('qquoteadv')->betaIsEnabled(Mage::app()->getStore()->getStoreId())): ?>
            <div class="shipping-estimates">
                <input style="display:none;" type='submit' onclick="requestShippingProposal();" name='submitShipRequest'
                       id="submitShipRequest" class='form-button' value="<?php echo $this->__('Request quote') ?>"/>
                <button onclick="$('submitShipRequest').click();event.preventDefault();  event.stopPropagation();"
                        class="button btn-estimate" id="shipEstimates"
                        title="<?php echo $this->__('Get Shipping Estimates') ?>" type="button">
                    <span><span><?php echo $this->__('Get Shipping Estimates') ?></span></span>
                </button>
            </div>
        <?php //endif; ?>
    </div>
</div>


<div id="billDiv">
    <h2><?php echo $this->__('Billing details') ?></h2>

    <p><?php echo $this->__("Enter your billing address details.") ?></p>


    <table id="qquote-tbl-billing" cellspacing='3' cellpadding='3' border="0" width="100%">
        <?php
            echo $this->getMultipleLineAddress('billing');
        ?>
        <tr>
            <td class="left">
                <?php echo Mage::helper('sales')->__('Zip/Postal Code') ?> <span class="required"></span><br/>
                <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type='text'
                       value="<?php echo $this->getValue('postcode', 'billing'); ?>" name='customer[postcode]'
                       id='customer:postcode' class="required-entry input-text w224"/>
            </td>
            <td class="p5">
                <?php echo Mage::helper('sales')->__('City') ?> <span class="required"></span><br/>
                <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type='text'
                       value="<?php echo $this->getValue('city', 'billing'); ?>" name='customer[city]'
                       id='customer:city' class="required-entry input-text w224"/>
            </td>

        </tr>

        <?php //$countryCode = $this->getValue('country', 'billing'); ?>
        <?php //if (empty($countryCode)) { $countryCode = null; } ?>

        <tr>
            <td class="left">
                <?php echo Mage::helper('sales')->__('Country') ?> <span class="required"></span><br/>
                <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getValue('country_id', 'billing'), 'customer[country_id]', 'country', Mage::helper('sales')->__('Country')) ?>
            </td>
            <td class="p5">
                <?php if($formOptionAddressState > 0){ ?>
                    <?php
                    echo Mage::helper('sales')->__('State/Province');
                    if($formOptionAddressState == 2){
                        echo '<span class="required"></span>';
                    }
                    ?><br/>
                    <select name='customer[region_id]' id='region_id'
                            title="<?php echo Mage::helper('sales')->__('State/Province') ?>"
                            class="<?php if($formOptionAddressState == 2){ echo 'required-entry'; } ?> validate-select w224"
                            style="display:none;">
                        <option value=""><?php echo $this->getValue('region_id', 'billing'); ?></option>
                    </select>
                    <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type="text"
                           name='customer[region]'
                           id='region' value="<?php echo $this->getValue('region', 'billing'); ?>"
                           title="<?php echo Mage::helper('sales')->__('State/Province') ?>"
                           class="<?php if($formOptionAddressState == 2){ echo 'required-entry'; } ?> input-text w224"/>
                <?php } else { ?>
                    <input name='customer[region_id]' id='region_id'
                           title="<?php echo Mage::helper('sales')->__('State/Province') ?>" type="hidden" />
                <?php } ?>
            </td>
        </tr>
        <?php
        // Adding extra option fields
        // pass Option Types as argument
        // to getExtraoptionsForm()
        $extraOptions = Mage::getModel('qquoteadv/extraoptions')->getExtraoptionsForm(array());

        if ($extraOptions != NULL):
            foreach ($extraOptions as $option):
                $pos1 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS1;
                $pos2 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS2;
                ?>
                <tr>
                    <td class="left">
                        <?php
                        if ($option[$pos1] != NULL):
                            $required = (isset($option[$pos1]['required'])) ? $option[$pos1]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos1], $required);
                        endif; ?>
                    </td>
                    <td class="p5">
                        <?php
                        if ($option[$pos2] != NULL):
                            $required = (isset($option[$pos2]['required'])) ? $option[$pos2]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos2], $required);
                        endif;?>
                    </td>
                </tr>
            <?php
            endforeach;
        endif;
        ?>
    </table>
    <div id="addressCheckbox">
        <?php if ($requireBilling && !$requireShipping): ?>
            <div class="inline-checkbox">
                <input id="chkBill" type="checkbox" checked="checked" name="customer[shipIsBill]">
                <label><?php echo $this->__('Shipping Address is same as Billing Address'); ?></label>
            </div>
        <?php endif; ?>
    </div>
</div>


<div id="optionsDiv">
    <h2><?php echo $this->__('Delivery Options') ?></h2>

    <p><?php echo $this->__("We offer the following delivery options. Multiple options can be selected.") ?></p>
    <table id="qquote-tbl-options" cellspacing='3' cellpadding='3' border="0" width="100%">
        <?php
        // Adding extra option fields
        // pass Option Types as argument
        // to getExtraoptionsForm()
        $extraOptions = Mage::getModel('qquoteadv/extraoptions')->getExtraoptionsForm(array());

        if ($extraOptions != NULL):
            foreach ($extraOptions as $option):
                $pos1 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS1;
                $pos2 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS2;
                ?>
                <tr>
                    <td class="left">
                        <?php
                        if ($option[$pos1] != NULL):
                            $required = (isset($option[$pos1]['required'])) ? $option[$pos1]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos1], $required);
                        endif; ?>
                    </td>
                    <td class="p5">
                        <?php
                        if ($option[$pos2] != NULL):
                            $required = (isset($option[$pos2]['required'])) ? $option[$pos2]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos2], $required);
                        endif;?>
                    </td>
                </tr>
            <?php
            endforeach;
        endif;
        ?>
    </table>
</div>

</div>
</div>
<?php if (Mage::getStoreConfig('qquoteadv_quote_form_builder/options/newsletter_subscribe')): ?>
    <div id="signup-newsletter">
        <div class="quote-forms">
            <div class="inline-checkbox">
                <input id="chkNews" type="checkbox" name="newsletter">
                <label for="chkNews"><?php echo Mage::helper('newsletter')->__('Sign up for our newsletter'); ?></label>
            </div>
        </div>
    </div>
<?php endif; ?>
<div class="quote-forms">
    <div id="submit-quote-request">
        <label for="submitOrder"><?php echo $this->__('You may request a quote without any obligations')?></label>
        <input type='hidden' id='customer_isQuote' name='customer[is_quote]' value='1'/>
        <input style="display:none;" type='submit' name='submitOrder' id="submitOrder" class='form-button'
               value="<?php echo $this->__('Request quote') ?>"/>

        <button onclick="$('submitOrder').click(); event.preventDefault();  event.stopPropagation();"
                class="button btn-proceed-checkout btn-checkout"
                title="<?php echo $this->__('Request quote') ?>" type="button">
            <span><span><?php echo $this->__('Request quote') ?></span></span>
        </button>
    </div>
</div>
</div>

<script type="text/javascript">
    //<![CDATA[
    var elmEmail = $('customer:email');
    var elmEmailMsg = $('email_message');
    var btnSubm = $('submitOrder');
    if (elmEmail) {
        Event.observe(elmEmail, 'keydown', function (event) {
            var e = event || window.event;
            if (btnSubm) {
                btnSubm.disabled = false;
            }
            if (e) {
                if (e.keyCode == 13) return false;
            }
        });

        Event.observe(elmEmail, 'click', function (event) {
            cssFailClass = 'validation-failed';
            if (elmEmail.hasClassName(cssFailClass)) {
                elmEmail.removeClassName(cssFailClass);
                elmEmail.value = '';

                elmEmailMsg.hide();
                elmEmailMsg.removeClassName('validation-advice');

                if (btnSubm) {
                    btnSubm.setStyle({background: '#F18200'});
                    btnSubm.disabled = false;
                }
            }
        });
    }
    //]]>
</script>

<?php if (!Mage::getStoreConfig('qquoteadv_quote_frontend/shoppingcart_quotelist/disable_exist_account_check')):
    ?>
    <script type="text/javascript">
        //<![CDATA[
        var elmEmail = $('customer:email');
        if (elmEmail) {
            var url = '<?php echo $this->getUrl('qquoteadv/index/useJsEmail') ?>';
            var message = '<?php echo $this->__('Customer email already exists. You should login <a href=%s>here</a>', $this->getLoginUrl()) ?>';

            Event.observe(elmEmail, 'change', function (event) {
                isExistUserEmail(event, url, message)
            });
        }//]]>
    </script>
<?php endif; ?>
<script type="text/javascript">
    var requireShipping = <?php echo !empty($requireShipping)  && !is_null($requireShipping)? 1: 0; ?>;
    var requireBilling = <?php echo !empty($requireBilling) && !is_null($requireBilling) ? 1: 0; ?>;
    var requireExtraOptions = <?php echo !empty($requireExtraOptions) && !is_null($requireExtraOptions) ? 1: 0; ?>;
    var isLoggedIn = <?php echo $this->isCustomerLoggedIn() ? 1 :0;?>;
    var shippingRatesRequested = <?php echo $shippingRatesRequested ? 1 :0;?>;

    if (requireExtraOptions == 0) {
        hide($('optionsDiv'));
    }
    if (requireBilling == 0) {
        hide($('billDiv'));
    }
    if ((requireShipping == 0) && (shippingRatesRequested == 0)) {
        hide($('shipDiv'));
    }
    if (isLoggedIn == 1) {
        hide($('billing-new-address-form'));
        hide($('chkShip'));
    }
    if ($('default_billing_shipping_address_checkbox') != null) {
        $('default_billing_shipping_address_checkbox').observe('change', function () {
            if ($('default_billing_shipping_address_checkbox').checked !== true) {
                show($('billing-new-address-form'), false);
                if ($('chkBill').checked !== true) {
                    show($('billDiv'));
                }
                show($('shipDiv'));
            } else {
                if (isLoggedIn) {
                    hide($('billing-new-address-form'), false);
                }
                if (requireBilling == 0) {
                    hide($('billDiv'), true);
                }
                if (requireShipping == 0) {
                    hide($('shipDiv'), true);
                }
                if ($('chkBill') != null) {
                    $('chkBill').checked = true;
                }
            }
        });
    }
    if ($('chkBill') != null) {
        $('chkBill').observe('change', function () {
            if ($('chkBill').checked === true) {
                if (requireBilling == 0) {
                    hide($('billDiv'));
                } else {
                    hide($('shipDiv'));
                }
            } else {
                if (requireBilling == 0) {
                    show($('billDiv'));
                } else {
                    show($('shipDiv'));
                }
            }
        });
    }
    if ($('chkShip') != null) {
        $('chkShip').observe('change', function () {
            $('shipDiv').toggle();
            if ($('chkBill').checked !== true) {
                $('billDiv').toggle();
            }
        });
    }
    function show(element) {
        if (element != null) {

            element.show();

        }
    }
    function hide(element) {
        if (element != null) {
            element.hide();
        }
    }
</script>
