<?php $_dld_color_title = Mage::helper('dailydeal')->getConfigSchemeColor(); ?>
<?php $_dld_color_coundown = Mage::helper('dailydeal')->getConfigCountdownColor(); ?>
<?php $_dld_color_lighight = Mage::helper('dailydeal')->getConfigHighlightColor(); ?> 
<?php
	function colourBrightnesstab($hex, $percent) {
	$hash = '';
	if (stristr($hex,'#')) {
		$hex = str_replace('#','',$hex);
		$hash = '#';
	}
	/// HEX TO RGB
	$rgb = array(hexdec(substr($hex,0,2)), hexdec(substr($hex,2,2)), hexdec(substr($hex,4,2)));
	//// CALCULATE
	for ($i=0; $i<3; $i++) {
		// See if brighter or darker
		if ($percent > 0) {
			// Lighter
			$rgb[$i] = round($rgb[$i] * $percent) + round(255 * (1-$percent));
		} else {
			// Darker
			$positivePercent = $percent - ($percent*2);
			$rgb[$i] = round($rgb[$i] * $positivePercent) + round(0 * (1-$positivePercent));
		}
		// In case rounding up causes us to go to 256
		if ($rgb[$i] > 255) {
			$rgb[$i] = 255;
		}
	}
	//// RBG to Hex
	$hex = '';
	for($i=0; $i < 3; $i++) {
		// Convert the decimal digit to hex
		$hexDigit = dechex($rgb[$i]);
		// Add a leading zero if necessary
		if(strlen($hexDigit) == 1) {
		$hexDigit = "0" . $hexDigit;
		}
		// Append to the hex string
		$hex .= $hexDigit;
	}
	return $hash.$hex;
}
?>

<style type="text/css">
	.tab-deal td.active a span ,
	.tab-deal td a:hover span{ background: <?php echo $_dld_color_title; ?>; background: <?php echo colourBrightnesstab($_dld_color_title,0.9);?> linear-gradient(to bottom, <?php echo colourBrightnesstab($_dld_color_title,0.9);?>, <?php echo colourBrightnesstab($_dld_color_title,-0.7);?>);}
	.tab-deal td.active a span span ,
	.tab-deal td a:hover span span{background: none;}
</style>
<table class="tab-deal">
    <tr>
        <td class="active">
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/index'); ?>">
                <span><span><?php echo $this->__('Current Deals'); ?></span></span>
            </a>
        </td>
        <td>
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/past'); ?>">
                <span><span><?php echo $this->__('Past Deals'); ?></span></span>
            </a>
        </td>
        <td>
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/comming'); ?>">
                <span><span><?php echo $this->__('Upcoming Deals'); ?></span></span>
            </a>
        </td>
    </tr>
</table>

<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$_activedealsCollection = $this->getActivedeals();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_activedealsCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products responsive-list list-actdeals">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_activedealsCollection as $_activedeal): ?>
                    <?php
                    $dealqty = $_activedeal->getDealQty();
                    $soldqty = $_activedeal->getSoldQty();
                    $_product = Mage::getModel('catalog/product')->load($_activedeal->getProductId());
                    ?>
                    <li class="item<?php if (++$_iterator == sizeof($_activedealsCollection)): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h2>
                                <?php if ($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                <?php endif; ?>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php if ($_product->isSaleable()): ?>
                                    <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
								<?php /*----- display daily deal -----*/ ?>
								<?php 
									$countdown = $this->getLayout()->createBlock('dailydeal/deal');
									$countdown->setData('product', $_product);
									echo $countdown->setTemplate('glace_dailydeal/catalog/product/countdown.phtml')->toHtml(); 
								?>
								<?php /*----- end display daily deal -----*/ ?>
                                <div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>

                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

            <?php // Grid Mode  ?>

            <?php
            $_collectionSize = $_activedealsCollection->count();
            $columncount = Mage::getStoreConfig('dailydeal/general/columncount'); //echo $columncount;die;
            $_columnCount = $columncount ? $columncount : 3; //$this->getColumnCount(); echo $_columnCount;die;
            ?>
            <?php
            $i = 0;
            foreach ($_activedealsCollection as $_activedeal):
                ?>
                <?php
                $dealqty = $_activedeal->getDealQty();
                $soldqty = $_activedeal->getSoldQty();

                $_product = Mage::getModel('catalog/product')->load($_activedeal->getProductId());
                ?>
                <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid items-columns<?php echo $_columnCount;?>">
                    <?php endif ?>
                    <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                       <div class="glace_pro_dld">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
							<?php /*----- display daily deal -----*/ ?>
							<?php 
								$countdown = $this->getLayout()->createBlock('dailydeal/deal');
								$countdown->setData('product', $_product);
								echo $countdown->setTemplate('glace_dailydeal/catalog/product/countdown.phtml')->toHtml(); 
							?>
							<?php /*----- end display daily deal -----*/ ?>
							<?php if($_product->getRatingSummary()): ?>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
							<?php endif; ?>
							<?php echo $this->getPriceHtml($_product, true) ?>
						</div>
                        <div class="actions">
                            <?php if ($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </li>
                    <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                    </ul>
                <?php endif ?>
            <?php endforeach ?>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php endif; ?>

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>
