<div class="deal">
				<div class="deal-title">
					<h1 class="deal-name">$15 for a Vintage-Style St. Patrick’s Day T-Shirt (a $32 Value). Multiple Styles and Gender Specific Sizes Available.</h1>
					<h2 class="product-name">St. Patrick’s Day T-Shirt – Online Deal</h2>
				</div>
				<div class="deal-info">
					<div class="leftcol">
												<div class="price_tag">
						  <div class="price_tag_inner">
							<div class="amount">NR15</div>	
								
								<div class="btn_buy">
									<a href="http://grouponclone.adolstore.com/demo/index.php/st-patrick-s-day-t-shirt-online-deal.html?options=cart" style="text-decoration:none;" class="show_config_options"><span>BUY NOW</span></a>
								</div>
														

						  </div>
						</div>
							<div class="deal_discount" class="clearfix">
		  <dl>
			<dt>Value</dt>
			<dd>NR32</dd>
		  </dl>
		  <dl class="discount">
			<dt>Discount</dt>
			<dd>53.1%</dd>
		  </dl>
		  <dl class="save">
			<dt>You Save</dt>
			<dd>NR17</dd>
		  </dl>
		  <div class="clear"></div>
	</div>							
<div id="gift_a_deal">
  
  <a class="icon_gift for_friend" href="http://grouponclone.adolstore.com/demo/index.php/st-patrick-s-day-t-shirt-online-deal.html?options=cart">Buy it for a friend!</a>
</div>	
						
										
	<div class="remaining_time">
		<p class="timer_text">Time left to Buy</p>
		<div class="timercontainer" id="cdcontainer_1"></div>
		<script type="text/javascript">					
			var dealActiveUntil = new Date();
			dealActiveUntil.setTime(1371805200000);
			var serverNow = new Date();
			serverNow.setSeconds(serverNow.getSeconds() + -25200);
			var launchdate_1=new cdLocalTime("cdcontainer_1", "server-php", 0, dealActiveUntil.toString(), serverNow.toUTCString());
			launchdate_1.displaycountdown("days", formatresults3);
		</script>
	</div>						<div class="share">
<!-- AddThis Button BEGIN -->
<div class="addthis_toolbox addthis_default_style" addthis:url="http://grouponclone.adolstore.com/demo/index.php/st-patrick-s-day-t-shirt-online-deal.html">
<a href="http://www.addthis.com/bookmark.php?v=250&amp;pubid=xa-4e3ae04f7ebb25c0" class="addthis_button_compact">Share</a>
<span class="addthis_separator">|</span>
  <a class="addthis_button_preferred_2"></a>
  <a class="addthis_button_preferred_3"></a>
  <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
  <a class="addthis_button_tweet"></a>
  <a class="addthis_button_google_plusone"></a>
</div>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-4e3ae04f7ebb25c0"></script>
<!-- AddThis Button END -->
</div>					</div>
					<div class="rightcol">
						
<div class="media">	
<img src="http://grouponclone.adolstore.com/demo/media/catalog/product/cache/1/small_image/440x267/9df78eab33525d08d6e5fb8d27136e95/9/6/96bcd937a6_grid_6.jpg" 
width="440" height="267" alt="St. Patrick’s Day T-Shirt – Online Deal" />
</div>
						
<div class="info">	
	<div class="fineprint">
		<h3>Fineprint</h3>
		<p>Limit 1 per person. Extra $3 fee for shipping. Does not ship to AK/HI/Canada. Ships out in 7-10 business days from purchase date. Does not ship to PO boxes</p>	</div>
	<div class="highlight">
		<h3>Highlights</h3>
		<p>Soft men&rsquo;s or women&rsquo;s St. Patrick&rsquo;s Day T-shirt in one of two styles &amp; multiple sizes with vintage-style witticism</p>	</div>
</div>					</div>
					<div class="clear"></div>
					
	<div class="deal-tabs">
		<ul class="1-product-tabs info-tabs">
			<li id="1-product_tabs_description"  class="first active" >
				<a href="javascript:void(0)">Description</a>
			</li>
			<li id="1-product_tabs_location">
				<a href="javascript:void(0)">Location</a>
			</li>
			<li id="1-product_tabs_reviews">
				<a href="javascript:void(0)">Reviews</a>
			</li>			
		</ul>
		<div class="product-tabs-content" id="1-product_tabs_contents">
			<div id="1-product_tabs_description_contents">
				<p>Each of these shamrock-green T-shirts sports a St. Patrick's Day witticism that advertises your playful spirit and Irish patriotism. Worn lettering lends the soft cotton-blend V-neck T-shirts a distinctly vintage feel. Affirm your ancestry with the &ldquo;Irish You Were Hot Like Me&rdquo; design or seek pecks from fellow celebrants or androids who've just had their heritage chip installed with the flirtatious &ldquo;Kiss Me You&rsquo;re Irish&rdquo; top.</p>			</div>		
			<div id="1-product_tabs_location_contents">
				<div class="deal_location">
					<h4>Deal address</h4>
					<p>10392 N Scottsdale Rd. <br /> Scottsdale, Arizona 85253 <br /> (480) 998-2222 <br /> Get Directions</p>				</div>
				<div class="deal_location_map">
					<p><iframe src="http://maps.google.com/maps?f=d&amp;daddr=110+S+Jackson+St.+Media+Pennsylvania+19063&amp;ie=UTF8&amp;ll=39.917537,-75.389557&amp;spn=0.0079,0.013733&amp;z=16&amp;output=embed" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" width="640" height="480"></iframe></p>				</div>
				<div class="clear"></div>
			</div>
			<div id="1-product_tabs_reviews_contents">
								<div class="product-collateral">	
				<div class="box-collateral box-reviews" id="customer-reviews">
    </div><div class="form-add">
    <h2>Write Your Own Review</h2>
        <form action="http://grouponclone.adolstore.com/demo/index.php/review/product/post/id/1/" method="post" id="review-form">
        <fieldset>
                        <h3>You're reviewing : <span>St. Patrick’s Day T-Shirt – Online Deal</span></h3>
                            <ul class="form-list">
                    <li>
                        <label for="nickname_field" class="required"><em>*</em>Nickname</label>
                        <div class="input-box">
                            <input type="text" name="nickname" id="nickname_field" class="input-text required-entry" value="" />
                        </div>
                    </li>
                    <li>
                        <label for="summary_field" class="required"><em>*</em>Summary of Your Review</label>
                        <div class="input-box">
                            <input type="text" name="title" id="summary_field" class="input-text required-entry" value="" />
                        </div>
                    </li>
                    <li>
                        <label for="review_field" class="required"><em>*</em>Review</label>
                        <div class="input-box">
                            <textarea name="detail" id="review_field" cols="5" rows="3" class="required-entry"></textarea>
                        </div>
                    </li>
                </ul>
            </fieldset>
            <div class="buttons-set">
                <button type="submit" title="Submit Review" class="button"><span><span>Submit Review</span></span></button>
            </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('review-form');
        Validation.addAllThese(
        [
               ['validate-rating', 'Please select one of each of the ratings above', function(v) {
                    var trs = $('product-review-table').select('tr');
                    var inputs;
                    var error = 1;
    
                    for( var j=0; j < trs.length; j++ ) {
                        var tr = trs[j];
                        if( j > 0 ) {
                            inputs = tr.select('input');
    
                            for( i in inputs ) {
                                if( inputs[i].checked == true ) {
                                    error = 0;
                                }
                            }
    
                            if( error == 1 ) {
                                return false;
                            } else {
                                error = 1;
                            }
                        }
                    }
                    return true;
                }]
        ]
        );
    //]]>
    </script>
    </div>
				</div>				
				
			</div>						
		</div>
	</div>
	<script>
		new Varien.Tabs('.1-product-tabs');
	</script>			
				</div>
			</div>