<?php $_dld_color_title = Mage::helper('dailydeal')->getConfigSchemeColor(); ?>
<?php $_dld_color_coundown = Mage::helper('dailydeal')->getConfigCountdownColor(); ?>
<?php $_dld_color_lighight = Mage::helper('dailydeal')->getConfigHighlightColor(); ?> 

<table class="tab-deal">
    <tr>
        <td class="active">
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/index'); ?>">
                <span><span><?php echo $this->__('Current Deals'); ?></span></span>
            </a>
        </td>
        <td>
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/past'); ?>">
                <span><span><?php echo $this->__('Past Deals'); ?></span></span>
            </a>
        </td>
        <td>
            <a href="<?php echo Mage::helper('dailydeal')->getUrlHttp('dailydeal/comming'); ?>">
                <span><span><?php echo $this->__('Upcoming Deals'); ?></span></span>
            </a>
        </td>
    </tr>
</table>

<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php
$_activedealsCollection = $this->getActivedeals();
$_helper = $this->helper('catalog/output');
?>
<?php if (!$_activedealsCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products responsive-list list-actdeals">
        <?php echo $this->getToolbarHtml() ?>
        <?php // List mode ?>
        <?php if ($this->getMode() != 'grid'): ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_activedealsCollection as $_activedeal): ?>
                    <?php
                    $dealqty = $_activedeal->getDealQty();
                    $soldqty = $_activedeal->getSoldQty();
                    $_product = Mage::getModel('catalog/product')->load($_activedeal->getProductId());
                    ?>
                    <li class="item<?php if (++$_iterator == sizeof($_activedealsCollection)): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="image-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix"> 
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h2>
                                <?php if ($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                <?php endif; ?>
                                <?php //echo $this->getPriceHtml($_product, true) ?>
<?php
                                $_coreHelper = $this->helper('core');
                                $_taxHelper = $this->helper('tax');
                                $_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice());
                                $_finalPrice = $_activedeal->getDailydealPrice();
                                ?>
                                <?php if($_activedeal->checkDealPrice($_product)){ ?>
                                <p class="old-price" >
                                <?php echo Mage::helper('dailydeal')->__('Regular Price:'); ?>
                                <span class="regular-price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>-related">
                                    <span class="price"><?php echo $_coreHelper->currency($_regularPrice, true, false) ?></span>
                                </span>
                            </p>
                            
                            <p class="special-price">
                                <span class="price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                                    <?php echo Mage::helper('dailydeal')->__('Special Price:'); ?>
                                    <?php echo $_coreHelper->currency($_finalPrice, true, false) ?>
                                </span>
                            </p>
                            <?php }else{
                                $_activedeal->setMinPriceFollowProductType($_product);?>
                            <p class="special-price">
                                <span class="price" id="product-price-<?php echo $_id ?><?php echo $this->getIdSuffix() ?>">
                                    <?php echo Mage::helper('dailydeal')->__('Special Price:'); ?>
            <?php echo $_coreHelper->currency($_product->getData('min_price'), true, false) ?>
                                </span>
                            </p>
                                
                            <?php } ?>

                                <div class="glacedld_coming_date">
                                    <?php if ($soldqty > 1 || $soldqty == 0) { ?>
                                        <?php echo Mage::helper('dailydeal')->__('There are <span class="deal-qty-one">%s items</span> sold.', $soldqty); ?> 				
                                    <?php } elseif ($soldqty == 1) { ?>
                                        <?php echo Mage::helper('dailydeal')->__('There are <span class="deal-qty-one">%s items</span> sold.', $soldqty); ?> 				
                                    <?php } ?>	            
                                </div>
                                <div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>

                                <ul class="add-to-links">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

        <?php else: ?>

            <?php // Grid Mode  ?>

            <?php
            $_collectionSize = $_activedealsCollection->count();
            $columncount = Mage::getStoreConfig('dailydeal/general/columncount'); //echo $columncount;die;
            $_columnCount = $columncount ? $columncount : 3; //$this->getColumnCount(); echo $_columnCount;die;
            ?>
            <?php
            $i = 0;
            foreach ($_activedealsCollection as $_activedeal):
                ?>
                <?php
                $dealqty = $_activedeal->getDealQty();
                $soldqty = $_activedeal->getSoldQty();

                $_product = Mage::getModel('catalog/product')->load($_activedeal->getProductId());
                ?>
                <?php if ($i++ % $_columnCount == 0): ?>
                    <ul class="products-grid items-columns<?php echo $_columnCount;?>">
                    <?php endif ?>
                    <li class="item<?php if (($i - 1) % $_columnCount == 0): ?> first<?php elseif ($i % $_columnCount == 0): ?> last<?php endif; ?>">
                       <div class="glace_pro_dld">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img class="image-responsive" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
							<h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
							<?php /*----- display daily deal -----*/ ?>
							<?php 
								$countdown = $this->getLayout()->createBlock('dailydeal/deal');
								$countdown->setData('product', $_product);
								echo $countdown->setTemplate('glace_dailydeal/catalog/product/countdown.phtml')->toHtml(); 
							?>
							<?php /*----- end display daily deal -----*/ ?>
							<?php if($_product->getRatingSummary()): ?>
								<?php echo $this->getReviewsSummaryHtml($_product, 'short'); ?>
							<?php endif; ?>
							<?php
							
							//echo $_product->getPrice();
							echo $this->getPriceHtml($_product, true); ?>
						</div>
                        <div class="actions">
                            <?php if ($_product->isSaleable()): ?>
                                <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                            <?php else: ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif; ?>
                            <ul class="add-to-links">
                                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                <?php endif; ?>
                                <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                                    <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                <?php endif; ?>
                            </ul>
                        </div>
                    </li>
                    <?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
                    </ul>
                	<?php endif; ?>
            <?php endforeach; ?>
            <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
        <?php endif; ?>

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>
    </div>
<?php endif; ?>
