<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2015] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2015 Cart2Quote B.V. (http://www.cart2quote.com)
 * @license     http://www.cart2quote.com/ordering-licenses
 */

// get billing email
$billingEmail = $this->getValue('email', 'billing');

// get required data
$requireShipping = (Mage::getStoreConfig('qquoteadv_quote_form_builder/options/require_shipping')) ? true : false;
$requireBilling = (Mage::getStoreConfig('qquoteadv_quote_form_builder/options/require_billing')) ? true : false;
$requireExtraOptions = (Mage::getStoreConfig('qquoteadv_quote_form_builder/options/require_delivery_options')) ? true : false;

// get form builder settings
$formOptionAccountTelephone = Mage::getStoreConfig('qquoteadv_quote_form_builder/account_details/telephone');
$formOptionAccountCompany   = Mage::getStoreConfig('qquoteadv_quote_form_builder/account_details/company');
$formOptionAccountVattaxid  = Mage::getStoreConfig('qquoteadv_quote_form_builder/account_details/vattaxid');
$formOptionAddressState     = Mage::getStoreConfig('qquoteadv_quote_form_builder/address_details/state');

// get customer from session
$customer = $this->getCustomerSession()->getCustomer();

// Retrieve Customer Request data from session
$client_request = "";
if($quoteData = $this->getCustomerSession()->getQuoteData()){
    if(isset($quoteData['customer']['client_request'])){
        $client_request = $quoteData['customer']['client_request'];
    }
    $customer->addData($quoteData['customer']);
} else {
    //get persisent client request
    $quoteId = $this->getCustomerSession()->getQuoteadvId();
    if ($quoteCustomer = Mage::getModel('qquoteadv/qqadvcustomer')->load($quoteId)) {
        $client_request = $quoteCustomer->getClientRequest();
        if (!isset($client_request) || empty($client_request)) {
            $client_request = $customer->getData('client_request');
        }
    } else {
        $client_request = $customer->getData('client_request');
    }
}

// Add customer information after shipping estimate request
if ($quoteCustomer = Mage::getSingleton('customer/session')->getData('quoteCustomer')) {
    $customer->addData($quoteCustomer->getData());
}

?>

<div class="qquote-client-collaterals">
<div class="client-data box">
<h4><?php echo Mage::helper('qquoteadv')->__('Remarks') ?> </h4>

<?php echo $this->__('Do you have a general remark with your quote request?') ?>
<br/>
<textarea name="customer[client_request]" id="customer:client_request" cols="10" rows="5" style="width:95%;" class="input-text"><?php echo $client_request; ?></textarea>
<?php

?>

<?php if ($this->isCustomerLoggedIn() && !empty($billingEmail)): ?>
    <fieldset>
        <p>
            <?php if ($requireExtraOptions === false): ?>
                <input type="checkbox" name="billing_address" value="use_default_billing" checked="checked"
                       onclick="if(this.checked){    $('billing-new-address-form').hide();
                                                $('qquoteadv_shipping_box').hide();
                                                $('addressContainer').hide();
                                                $('billDiv').hide();
                                            }else{
                                                $('billing-new-address-form').show();
                                                $('qquoteadv_shipping_box').show();
                                                $('addressContainer').show();
                                                $('billDiv').show();
                                            }">
            <?php else: ?>
                <input type="checkbox" name="billing_address" value="use_default_billing" checked="checked"
                       onclick="if(this.checked){    $('billing-new-address-form').hide();
                                                $('qquoteadv_shipping_box').show();
                                                $('addressContainer').show();
                                                $('billDiv').hide();
                                                $('chkBill').hide();
                                                $('addressCheckbox').hide();
                                            }else{
                                                $('billing-new-address-form').show();
                                                $('qquoteadv_shipping_box').show();
                                                $('addressContainer').show();
                                                $('billDiv').show();
                                                $('chkBill').show();
                                                $('addressCheckbox').show();
                                            }">
            <?php endif; ?>

            &nbsp;<label
                for="customer:use_default_billing"><?php echo $this->__('Use Default Billing and Shipping Address') ?> </label>
        </p>
    </fieldset>
<?php endif; ?>

<?php if ($this->isCustomerLoggedIn() && !empty($billingEmail)): ?>
<div id="billing-new-address-form" style="display:none;">
<?php else: ?>
<div class="input-box">
    <?php endif; ?>
    <div id="accountDiv">
        <?php $email = $customer->getEmail() ? $customer->getEmail() : $this->getCustomerEmail() ?>
        <table id="qquote-tbl-address" cellspacing='6' cellpadding='3' border="0" width="100%">
            <tr>
                <td class="left">
                    <?php echo Mage::helper('sales')->__('Email Address') ?> <span class="required">*</span><br/>
                    <input <?php if (!empty($email)): ?>readonly="readonly"<?php endif; ?> type='text'
                           value="<?php echo $email; ?>"
                           name='customer[email]' id='customer:email'
                           class="validate-email required-entry input-text"/><span id="please-wait"
                                                                                   style="display:none;"><img
                            alt="<?php echo $this->__('Checking..') ?>"
                            src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>"/></span>

                    <div style="display:none;" id="email_message">&nbsp;</div>
                </td>
                <td class="p5">
                </td>
            </tr>
            <tr>
                <td class="left">
                    <?php echo Mage::helper('sales')->__('First Name') ?> <span class="required">*</span><br/>
                    <input type='text' value="<?php echo $customer->getData('firstname'); ?>"
                           name='customer[firstname]' id='customer:firstname' class="required-entry input-text"/>
                </td>
                <td class="p5">
                    <?php echo Mage::helper('sales')->__('Last Name') ?> <span class="required">*</span><br/>
                    <input type='text' value="<?php echo $customer->getData('lastname'); ?>"
                           name='customer[lastname]' id='customer:lastname' class="required-entry input-text"/>
                </td>

            </tr>
            <tr>
                <td class="left">
                    <?php
                    if($formOptionAccountTelephone != 0){
                        echo Mage::helper('sales')->__('Telephone');
                        if($formOptionAccountTelephone == 2){
                            echo '<span class="required">*</span>';
                        }
                    }
                    ?><br/>
                    <input type='<?php if($formOptionAccountTelephone == 0){ echo 'hidden'; } else {echo 'text'; } ?>'
                           value="<?php echo $this->getValue('telephone', 'billing') ?>"
                           name='customer[telephone]' id='customer:telephone'
                           class="<?php if($formOptionAccountTelephone == 2){ echo 'required-entry'; } ?> input-text"/>
                </td>
                <td class="p5">
                    <?php
                    if($formOptionAccountCompany != 0){
                        echo Mage::helper('sales')->__('Company');
                        if($formOptionAccountCompany == 2){
                            echo '<span class="required">*</span>';
                        }
                    }
                    ?><br/>
                    <input type='<?php if($formOptionAccountCompany == 0){ echo 'hidden'; } else {echo 'text'; } ?>'
                           value="<?php echo $this->getValue('company', 'billing') ?>"
                           name='customer[company]' id='customer:company'
                           class="<?php if($formOptionAccountCompany == 2){ echo 'required-entry'; } ?> input-text"/>
                </td>
            </tr>
            <tr>
                <td class="left">
                    <?php
                    if($formOptionAccountVattaxid != 0){
                        echo Mage::helper('customer')->__('VAT Number');
                        if($formOptionAccountVattaxid == 2){
                            echo '<span class="required">*</span>';
                        }
                    }
                    ?><br/>
                    <input type='<?php if($formOptionAccountVattaxid == 0){ echo 'hidden'; } else {echo 'text'; } ?>'
                           value="<?php echo $this->getValue('vat_id', 'billing') ?>"
                           name='customer[vat_id]' id='customer:vat_id'
                           class="<?php if($formOptionAccountVattaxid == 2){ echo 'required-entry'; } ?> input-text"/>
                </td>
                <td class="p5">
                </td>
            </tr>
            <?php echo $this->getChildHtml('qquote.extrafields'); ?>
            <?php
            // Adding extra option fields
            // pass Option Types as argument
            // to getExtraoptionsForm()
            $extraOptions = Mage::getModel('qquoteadv/extraoptions')->getExtraoptionsForm();

            if ($extraOptions != NULL):
                foreach ($extraOptions as $option):
                    $pos1 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS1;
                    $pos2 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS2;
                    ?>
                    <tr>
                        <td class="left">
                            <?php
                            if ($option[$pos1] != NULL):
                                $required = (isset($option[$pos1]['required'])) ? $option[$pos1]['required'] : false;
                                echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos1], $required);
                            endif; ?>
                        </td>
                        <td class="p5">
                            <?php
                            if ($option[$pos2] != NULL):
                                $required = (isset($option[$pos2]['required'])) ? $option[$pos2]['required'] : false;
                                echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos2], $required);
                            endif;?>
                        </td>
                    </tr>
                <?php
                endforeach;
            endif;
            ?>
        </table>
    </div>
</div>

<?php if (Mage::getStoreConfig('qquoteadv_quote_form_builder/options/newsletter_subscribe')): ?>
    <div>
        <input id="chkNews" type="checkbox"
               name="newsletter"> <?php echo Mage::helper('newsletter')->__('Sign up for our newsletter'); ?>
    </div>
<?php endif; ?>

<?php if (!$this->isCustomerLoggedIn()): ?>
    <?php
    $chkShipHidden = Mage::getStoreConfig('qquoteadv_quote_form_builder/options/hide_shipping_quote');
    if ($chkShipHidden){
        $chkShipType = 'hidden';
    } else {
        $chkShipType = 'checkbox';
    }
    ?>
    <div>

        <?php
        if ($requireShipping === false && $requireBilling === false):
            if ($requireExtraOptions === false):
                ?>
                <input id="chkShip" type="<?php echo $chkShipType; ?>"
                       onclick="if(this.checked){   $('addressContainer').show();
                                                        $('addressCheckbox').show();
                                                        $('shipDiv').show();
                                                    }else{
                                                        $('addressContainer').hide();
                                                        $('addressCheckbox').hide();
                                                        $('shipDiv').hide();
                                                    } ">
            <?php else: ?>
                <input id="chkShip" type="<?php echo $chkShipType; ?>"
                       onclick="if(this.checked){   $('addressContainer').show();
                                                        $('addressCheckbox').show();
                                                        $('shipDiv').show();
                                                    }else{
                                                        $('addressContainer').show();
                                                        $('addressCheckbox').hide();
                                                        $('shipDiv').hide();
                                                    } ">
            <?php endif; ?>
            <?php if(!$chkShipHidden){echo $this->__('Request a shipping quote');} ?>
        <?php endif; ?>
    </div>
<?php endif; ?>

</div>

<?php if ($this->isCustomerLoggedIn() && !empty($billingEmail)): ?>
<div id="qquoteadv_shipping_box"
     class="qquote-cart-collaterals" <?php if ($requireShipping === false && $requireBilling === false && $requireExtraOptions === false) {
    echo 'style="display:none;"';
} ?> >
<?php else: ?>
<div class="qquote-cart-collaterals">
<?php endif; ?>

<div id="addressContainer" class="shipping-adress box"
     style="<?php if ($requireShipping === false && $requireBilling === false && $requireExtraOptions === false): echo 'display:none;'; endif; ?>">
<div
    id="billDiv" <?php if ($requireBilling === false || ($this->isCustomerLoggedIn() && $requireBilling === false)): ?> style="display:none;" <?php endif; ?> >
    <h4><?php echo $this->__('Billing details') ?></h4>

    <p><?php echo $this->__("Enter your billing address details.") ?></p>


    <table id="qquote-tbl-billing" cellspacing='3' cellpadding='3' border="0" width="100%">
        <?php
            echo $this->getMultipleLineAddress('billing');
        ?>
        <tr>
            <td class="left">
                <?php echo Mage::helper('sales')->__('Zip/Postal Code') ?> <span class="required">*</span><br/>
                <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type='text'
                       value="<?php echo $this->getValue('postcode', 'billing'); ?>" name='customer[postcode]'
                       id='customer:postcode' class="required-entry input-text w224"/>
            </td>
            <td class="p5">
                <?php echo Mage::helper('sales')->__('City') ?> <span class="required">*</span><br/>
                <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type='text'
                       value="<?php echo $this->getValue('city', 'billing'); ?>" name='customer[city]'
                       id='customer:city' class="required-entry input-text w224"/>
            </td>

        </tr>

        <?php //$countryCode = $this->getValue('country', 'billing'); ?>
        <?php //if (empty($countryCode)) { $countryCode = null; } ?>

        <tr>
            <td class="left">
                <?php echo Mage::helper('sales')->__('Country') ?> <span class="required">*</span><br/>
                <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getValue('country_id', 'billing'), 'customer[country_id]', 'country', Mage::helper('sales')->__('Country')) ?>
            </td>
            <td class="p5">
                <?php if($formOptionAddressState > 0){ ?>
                    <?php
                    echo Mage::helper('sales')->__('State/Province');
                    if($formOptionAddressState == 2){
                        echo '<span class="required">*</span>';
                    }
                    ?><br/>
                    <select name='customer[region_id]' id='region_id'
                            title="<?php echo Mage::helper('sales')->__('State/Province') ?>"
                            class="<?php if($formOptionAddressState == 2){ echo 'required-entry'; } ?> validate-select w224"
                            style="display:none;">
                        <option value=""><?php echo $this->getValue('region_id', 'billing'); ?></option>
                    </select>
                    <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type="text" name='customer[region]'
                           id='region' value="<?php echo $this->getValue('region', 'billing'); ?>"
                           title="<?php echo Mage::helper('sales')->__('State/Province') ?>"
                           class="<?php if($formOptionAddressState == 2){ echo 'required-entry'; } ?>  input-text w224"
                           style="display:none;"/>
                <?php } else { ?>
                    <input name='customer[region_id]' id='region_id'
                           title="<?php echo Mage::helper('sales')->__('State/Province') ?>" type="hidden" />
                <?php } ?>
            </td>
        </tr>
        <?php
        // Adding extra option fields
        // pass Option Types as argument
        // to getExtraoptionsForm()
        $extraOptions = Mage::getModel('qquoteadv/extraoptions')->getExtraoptionsForm(array());

        if ($extraOptions != NULL):
            foreach ($extraOptions as $option):
                $pos1 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS1;
                $pos2 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS2;
                ?>
                <tr>
                    <td class="left">
                        <?php
                        if ($option[$pos1] != NULL):
                            $required = (isset($option[$pos1]['required'])) ? $option[$pos1]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos1], $required);
                        endif; ?>
                    </td>
                    <td class="p5">
                        <?php
                        if ($option[$pos2] != NULL):
                            $required = (isset($option[$pos2]['required'])) ? $option[$pos2]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos2], $required);
                        endif;?>
                    </td>
                </tr>
            <?php
            endforeach;
        endif;
        ?>
    </table>
</div>

<div id="shipDiv"
     style=" <?php if ($requireShipping === false || ($this->isCustomerLoggedIn() && $requireShipping === false && $requireBilling === false && $requireExtraOptions === false) || ($requireShipping === 1 && $requireBilling === 1)): echo 'display:none'; endif; ?>">
    <h4><?php echo $this->__('Shipping details') ?></h4>

    <p><?php echo $this->__("Enter your destination to receive a shipping quotation. Unless otherwise specified, standard shipping is quoted.") ?></p>


    <table id="qquote-tbl-shipping" cellspacing='3' cellpadding='3' border="0" width="100%">
        <?php
            echo $this->getMultipleLineAddress('shipping');
        ?>
        <tr>
            <td class="left">
                <?php echo Mage::helper('sales')->__('Zip/Postal Code') ?> <span class="required">*</span><br/>
                <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type='text'
                       value="<?php echo $this->getValue('postcode', 'shipping'); ?>" name='customer[shipping_postcode]'
                       id='customer:shipping_postcode' class="required-entry input-text w224"/>
            </td>
            <td class="p5"></td>
        </tr>
        <tr>

            <td class="left">
                <?php echo Mage::helper('sales')->__('City') ?> <span class="required">*</span><br/>
                <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type='text'
                       value="<?php echo $this->getValue('city', 'shipping'); ?>" name='customer[shipping_city]'
                       id='customer:shipping_city' class="required-entry input-text w224"/>
            </td>
            <td class="p5">
                <?php echo Mage::helper('sales')->__('Country') ?> <span class="required">*</span><br/>
                <?php echo Mage::getBlockSingleton('directory/data')->getCountryHtmlSelect($this->getValue('country_id', 'shipping'), 'customer[shipping_country_id]', 'shipping_country', Mage::helper('sales')->__('Country')) ?>
            </td>

        </tr>

        <?php //$countryCode = $this->getValue('country', 'billing'); ?>
        <?php //if (empty($countryCode)) { $countryCode = null; } ?>

        <tr>
            <td class="left">
                <?php if($formOptionAddressState > 0){ ?>
                    <?php
                    echo Mage::helper('sales')->__('State/Province');
                    if($formOptionAddressState == 2){
                        echo '<span class="required">*</span>';
                    }
                    ?><br/>
                    <select name='customer[shipping_region_id]' id='shipping_region_id'
                            title="<?php echo Mage::helper('sales')->__('State/Province') ?>"
                            class="<?php if($formOptionAddressState == 2){ echo 'required-entry'; } ?> validate-select w224"
                            style="display:none;">
                        <option value=""><?php echo $this->getValue('region_id', 'shipping'); ?></option>
                    </select>
                    <input onfocus="Element.setStyle(this, {color:'#2F2F2F'});" type="text" name='customer[shipping_region]'
                           id='shipping_region' value="<?php echo $this->getValue('region', 'shipping'); ?>"
                           title="<?php echo Mage::helper('sales')->__('State/Province') ?>"
                           class="<?php if($formOptionAddressState == 2){ echo 'required-entry'; } ?>  input-text w224"
                           style="display:none;"/>
                <?php } else { ?>
                    <input name='customer[region_id]' id='region_id'
                           title="<?php echo Mage::helper('sales')->__('State/Province') ?>" type="hidden" />
                <?php } ?>
            </td>
            <td class="p5">
                <?php
                $ratesList = array();
                if (count(Mage::getSingleton('customer/session')->getData('quoteRatesList')) > 0) {
                    $ratesList = Mage::getSingleton('customer/session')->getData('quoteRatesList');
                    echo $this->__('Shipping Estimate') . '<br />';
                    echo "<select id='shipping_method' name='customer[shipping_method]'>";
                    foreach ($ratesList as $rate) {
                        echo '<option value="' . $rate['value'] . '">' . $rate['option'] . '</option>';
                    }
                    echo "</select>";

                    Mage::getSingleton('customer/session')->unsetData('quoteRatesList', '');
                    Mage::getSingleton('customer/session')->unsetData('quotecustomer', '');
                }
                ?>
            </td>
        </tr>
        <?php
        // Adding extra option fields
        // pass Option Types as argument
        // to getExtraoptionsForm()
        $extraOptions = Mage::getModel('qquoteadv/extraoptions')->getExtraoptionsForm(array());

        if ($extraOptions != NULL):
            foreach ($extraOptions as $option):
                $pos1 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS1;
                $pos2 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS2;
                ?>
                <tr>
                    <td class="left">
                        <?php
                        if ($option[$pos1] != NULL):
                            $required = (isset($option[$pos1]['required'])) ? $option[$pos1]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos1], $required);
                        endif; ?>
                    </td>
                    <td class="p5">
                        <?php
                        if ($option[$pos2] != NULL):
                            $required = (isset($option[$pos2]['required'])) ? $option[$pos2]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos2], $required);
                        endif;?>
                    </td>
                </tr>
            <?php
            endforeach;
        endif;
        ?>
    </table>
</div>
<div id="addressCheckbox" style="<?php if (($requireBilling === false && $requireShipping === false) ||
    ($this->isCustomerLoggedIn() && ($requireBilling === false && $requireShipping === false))
) {
    echo 'display:none;';
}?>">
    <?php if (!$this->isCustomerLoggedIn() && $requireBilling === false): ?>
        <input id="chkBill" type="checkbox" checked="checked" name="customer[billIsShip]"
               onclick="if(this.checked){ $('billDiv').hide(); }else{ $('billDiv').show(); } "> <?php echo $this->__('Billing Address is same as Shipping Address'); ?>
    <?php elseif ($this->isCustomerLoggedIn()): ?>
        <input id="chkBill" type="checkbox" name="customer[shipIsBill]"
               onclick="if(this.checked){ $('shipDiv').hide(); }else{ $('shipDiv').show(); } "> <?php echo $this->__('Shipping Address is same as Billing Address'); ?>
    <?php
    else: ?>
        <input id="chkBill" type="checkbox" name="customer[shipIsBill]"
               onclick="if(this.checked){ $('shipDiv').hide(); }else{ $('shipDiv').show(); } "> <?php echo $this->__('Shipping Address is same as Billing Address'); ?>
    <?php endif; ?>
    <?php // BETA FEATURE
    //if (Mage::helper('qquoteadv')->betaIsEnabled(Mage::app()->getStore()->getStoreId())): ?>
        <div style="float:right; padding-right: 20px;">
            <input style="display:none;" type='submit' onclick="requestShippingProposal();" name='submitShipRequest'
                   id="submitShipRequest" class='form-button' value="<?php echo $this->__('Request quote') ?>"/>
            <button onclick="$('submitShipRequest').click();event.preventDefault();  event.stopPropagation();"
                    class="button btn-estimate" id="shipEstimates"
                    title="<?php echo $this->__('Get Shipping Estimates') ?>" type="button">
                <span><span><?php echo $this->__('Get Shipping Estimates') ?></span></span>
            </button>
        </div>
    <?php //endif; ?>
</div>


<div id="optionsDiv" style="<?php if ($requireExtraOptions === false): ?> display:none; <?php endif; ?> ">
    <h4><?php echo $this->__('Delivery Options') ?></h4>

    <p><?php echo $this->__("We offer the following delivery options. Multiple options can be selected.") ?></p>
    <table id="qquote-tbl-options" cellspacing='3' cellpadding='3' border="0" width="100%">
        <?php
        // Adding extra option fields
        // pass Option Types as argument
        // to getExtraoptionsForm()
        $extraOptions = Mage::getModel('qquoteadv/extraoptions')->getExtraoptionsForm(array());

        if ($extraOptions != NULL):
            foreach ($extraOptions as $option):
                $pos1 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS1;
                $pos2 = Ophirah_Qquoteadv_Model_Extraoptions::FORM_POS2;
                ?>
                <tr>
                    <td class="left">
                        <?php
                        if ($option[$pos1] != NULL):
                            $required = (isset($option[$pos1]['required'])) ? $option[$pos1]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos1], $required);
                        endif; ?>
                    </td>
                    <td class="p5">
                        <?php
                        if ($option[$pos2] != NULL):
                            $required = (isset($option[$pos2]['required'])) ? $option[$pos2]['required'] : false;
                            echo Mage::getModel('qquoteadv/extraoptions')->createInputHtml($option[$pos2], $required);
                        endif;?>
                    </td>
                </tr>
            <?php
            endforeach;
        endif;
        ?>
    </table>
</div>


<p class="required"><?php echo Mage::helper('sales')->__('* Required Fields') ?></p>
</div>
</div>


<script type="text/javascript">
    //<![CDATA[
    var elmEmail = $('customer:email');
    var elmEmailMsg = $('email_message');
    var btnSubm = $('submitOrder');
    if (elmEmail) {
        Event.observe(elmEmail, 'keydown', function (event) {
            var e = event || window.event;
            if (btnSubm) {
                btnSubm.disabled = false;
            }
            if (e) {
                if (e.keyCode == 13) return false;
            }
        });

        Event.observe(elmEmail, 'click', function (event) {
            cssFailClass = 'validation-failed';
            if (elmEmail.hasClassName(cssFailClass)) {
                elmEmail.removeClassName(cssFailClass);
                elmEmail.value = '';

                elmEmailMsg.hide();
                elmEmailMsg.removeClassName('validation-advice');

                if (btnSubm) {
                    btnSubm.setStyle({background: '#F18200'});
                    btnSubm.disabled = false;
                }
            }
        });
    }
    //]]>
</script>

<?php
$disable_check = Mage::getStoreConfig('qquoteadv_quote_frontend/shoppingcart_quotelist/disable_exist_account_check');
if (!$disable_check):
    ?>
    <script type="text/javascript">
        //<![CDATA[
        var elmEmail = $('customer:email');
        if (elmEmail) {
            var url = '<?php echo $this->getUrl('qquoteadv/index/useJsEmail') ?>';
            var message = '<?php echo $this->__('Customer email already exists. You should login <a href=%s>here</a>', $this->getLoginUrl()) ?>';

            Event.observe(elmEmail, 'change', function (event) {
                isExistUserEmail(event, url, message)
            });
        }//]]>
    </script>
<?php endif; ?>
