<?php $_helper = $this->helper('catalog/output'); ?> 
<?php $_product = $this->getData('product');?>

<?php
$currenttime = date('Y-m-d H:i:s', Mage::getModel('core/date')->timestamp(time()));
$_deal = Mage::getModel('dailydeal/dailydeal')->getCollection()->loadcurrentdeal($_product->getId());
if ($_deal) {
    Glace_Dailydeal_Model_Business::increateFeaturedView($_deal->getId());
    $title = Mage::getStoreConfig('dailydeal/general/productdetaillabel');
    $gmtcore = Mage::getSingleton('core/date')->getGmtOffset(); //var_dump($gmtcore*1000);die;
    $currenttime = Mage::getModel('core/date')->timestamp(time()); //var_dump($_deal->getEndDateTime());
    $beforetime = $currenttime - strtotime($_deal->getStartDateTime());
    $aftertime = strtotime($_deal->getEndDateTime()) - $currenttime;
    $timechange = (int) Mage::getStoreConfig('dailydeal/general/timechange');
    $dealqty = $_deal->getDealQty();
    $soldqty = $_deal->getSoldQty();
?>

	<?php
    if (Mage::helper('dailydeal')->getConfigIsShowImageCatalogList()) {
        $url = Mage::helper('dailydeal')->getUrlImageCatalogList();
        ?>
        <img class="glacedld_img_sale" src ="<?php echo $url ?>" alt="<?php echo $this->__('sale');?>"/>
    <?php } ?>


<link rel="stylesheet" href="<?php echo $this->getSkinUrl('glace_dailydeal/css/superneat.css') ?>" type="text/css" media="all"/>

<?php $_dld_color_title = Mage::helper('dailydeal')->getConfigSchemeColor(); ?>
<?php $_dld_color_coundown = Mage::helper('dailydeal')->getConfigCountdownColor(); ?>
<?php $_dld_color_lighight = Mage::helper('dailydeal')->getConfigHighlightColor(); ?>
<?php
	function colourBrightness_detail($hex, $percent) {
	$hash = '';
	if (stristr($hex,'#')) {
		$hex = str_replace('#','',$hex);
		$hash = '#';
	}
	/// HEX TO RGB
	$rgb = array(hexdec(substr($hex,0,2)), hexdec(substr($hex,2,2)), hexdec(substr($hex,4,2)));
	//// CALCULATE
	for ($i=0; $i<3; $i++) {
		// See if brighter or darker
		if ($percent > 0) {
			// Lighter
			$rgb[$i] = round($rgb[$i] * $percent) + round(255 * (1-$percent));
		} else {
			// Darker
			$positivePercent = $percent - ($percent*2);
			$rgb[$i] = round($rgb[$i] * $positivePercent) + round(0 * (1-$positivePercent));
		}
		// In case rounding up causes us to go to 256
		if ($rgb[$i] > 255) {
			$rgb[$i] = 255;
		}
	}
	//// RBG to Hex
	$hex = '';
	for($i=0; $i < 3; $i++) {
		// Convert the decimal digit to hex
		$hexDigit = dechex($rgb[$i]);
		// Add a leading zero if necessary
		if(strlen($hexDigit) == 1) {
		$hexDigit = "0" . $hexDigit;
		}
		// Append to the hex string
		$hex .= $hexDigit;
	}
	return $hash.$hex;
}
?>

<style type="text/css">
	.deal-product{box-shadow: 0 0 3px <?php echo $_dld_color_title; ?>; -moz-box-shadow: 0 0 3px <?php echo $_dld_color_title; ?>; -webkit-box-shadow: 0 0 3px <?php echo $_dld_color_title; ?>}
	.deal-product .catalogproductview{background-color: <?php echo $_dld_color_title; ?>; background-image: linear-gradient(to bottom, <?php echo colourBrightness_detail($_dld_color_title,0.9);?>, <?php echo colourBrightness_detail($_dld_color_title,-0.7);?>);}
	.qty-deal{background: <?php echo colourBrightness_detail($_dld_color_title,0.1);?>}
	.counter ul.countdown li div.countdown_num span{background: <?php echo $_dld_color_coundown; ?>}
	.qty-deal span.deal-qty{color: <?php echo $_dld_color_lighight;?>}
	.glace_dld_detail ul li span.glace_dld_detail_num{color: <?php echo $_dld_color_lighight;?>}
	.deal-product{border: 1px solid <?php echo $_dld_color_title; ?>\9;}
</style>    
    <div class="deal-product">
        <div class="catalogproductview">
            <?php if ($title == '') { ?>
                <h3><?php echo $this->__('Get it before it&acute;s gone!'); ?></h3>
            <?php } else { ?>
                <h3><?php echo $title; ?></h3>
            <?php } ?>
        </div>
        <div class="ct-deal-pro">
            <!-- Countdown Javascript -->
            <div id="counter" class="counter">
                <ul class="countdown">
                    <li class="first">
                        <div class="countdown_num" id="view_cd_day-<?php echo $_deal->getDailydealId() ?>"></div><div id="day"></div>
					</li>
                    <li>
                        <div class="countdown_num" id="view_cd_hour-<?php echo $_deal->getDailydealId() ?>"></div><div id="hour"></div>
					</li>
                    <li>
                        <div class="countdown_num" id="view_cd_min-<?php echo $_deal->getDailydealId() ?>"></div><div id="minute"></div>
					</li>
                    <li class="last">
                        <div class="countdown_num" id="view_cd_sec-<?php echo $_deal->getDailydealId() ?>"></div><div id="second"></div>
					</li>
                </ul>
            </div>
            <div id="expired" style="display:none;">
                <?php echo Mage::helper('dailydeal')->__('The deadline has passed.'); ?>
            </div>
            <script type="text/javascript">
                <?php 
                    $remain_second = strtotime($_deal->getEndDateTime()) - Mage::getModel('core/date')->timestamp();
                ?>
                var product_detail_server_time = {
                    second : <?php echo $remain_second; ?>,
                    callback : '',
                    
                    id_day  : 'view_cd_day-' + <?php echo $_deal->getId(); ?>,
                    id_hour  : 'view_cd_hour-' + <?php echo $_deal->getId(); ?>,
                    id_minute  : 'view_cd_min-' + <?php echo $_deal->getId(); ?>,
                    id_second  : 'view_cd_sec-' + <?php echo $_deal->getId(); ?>,
                    
                    label_day : 'day',
                    label_hour : 'hour',
                    label_minute : 'minute',
                    label_second : 'second'
                };
                countDownSecond(product_detail_server_time);
            </script>     
            <div class="clear"><span>&nbsp;</span></div>
            
            
			<?php if ( $_deal->checkDealQtyToShow($_product) && 
                    ( Mage::helper('dailydeal')->getConfigTodayDealShowDetail() || Mage::helper('dailydeal')->getConfigDisplayQuantity())) { ?>
            <div class="qty-deal">
                
                
                
                <?php if (Mage::helper('dailydeal')->getConfigTodayDealShowDetail()) {
						$_deal->processValueDiscountSaveBought(array('model_product' => $_product));
						$_deal_info = $_deal->getData('value_discount_save_bought');?>
						<div class="glace_dld_detail">
							<ul>
								<li>
									<span><?php echo Mage::helper('dailydeal')->__('Discount') ?></span>
									<span class="glace_dld_detail_num"><?php echo $_deal_info['discount'] ?></span>
								</li>
								<li>
									<span><?php echo Mage::helper('dailydeal')->__('You Save') ?></span>
									<span class="glace_dld_detail_num"><?php echo $_deal_info['you_save'] ?></span>
								</li>
								<li>
									<span><?php echo Mage::helper('dailydeal')->__('Bought') ?></span>
									<span class="glace_dld_detail_num"><?php echo $_deal_info['bought'] ?></span>
								</li>
							</ul>
						</div>
                <?php } ?>
                        
                        
                <?php if (Mage::helper('dailydeal')->getConfigDisplayQuantity()) { ?>
						<span>
							<?php
							if (($dealqty - $soldqty) > 10) {
								echo Mage::helper('dailydeal')->renderDealQtyOnProductPage($dealqty - $soldqty);
							} elseif (($dealqty - $soldqty) <= 10 && ($dealqty - $soldqty) > 1) {
								echo Mage::helper('dailydeal')->renderDealQtyOnProductPage($dealqty - $soldqty);
							} elseif (($dealqty - $soldqty) == 1) {
								echo Mage::helper('dailydeal')->renderDealQtyOnProductPage($dealqty - $soldqty);
							}
							?>
						</span>                        
                <?php } ?>
                
                </div>
			<?php } ?>
        </div>					
	</div>
<?php } ?>
