<?php 
$_coreHelper = $this->helper('core');
$_taxHelper = $this->helper('tax');
$title = Mage::getStoreConfig('dailydeal/general/title');
$_dealCollection = $this->getDeals();
$_collectionSize = count($_dealCollection);
if ($_collectionSize > 0):
    foreach ($_dealCollection as $_deal):
        Glace_Dailydeal_Model_Business::increateFeaturedView($_deal->getId());
        $dealqty = $_deal->getDealQty();
        $soldqty = $_deal->getSoldQty();
        $gmtcore = Mage::getSingleton('core/date')->getGmtOffset();
        $beforetime = Mage::getModel('core/date')->timestamp(time()) - strtotime($_deal->getStartDateTime());
        $aftertime = strtotime($_deal->getEndDateTime()) - Mage::getModel('core/date')->timestamp(time());
        if (($aftertime > 0) && ($beforetime >= 0)) {
            $_product = Mage::getModel('catalog/product')->load($_deal->getProductId());
            ?>
			
			<?php $_dld_color_title = Mage::helper('dailydeal')->getConfigSchemeColor(); ?>
			<?php $_dld_color_coundown = Mage::helper('dailydeal')->getConfigCountdownColor(); ?>
			<?php $_dld_color_lighight = Mage::helper('dailydeal')->getConfigHighlightColor(); ?> 
            <div class="block block-todaydeal" >
                <div class="title">
                    <?php if ($title == '') { ?>
                        <h3><?php echo $this->__('Get it before it&acute;s gone!'); ?></h3>
                    <?php } else { ?>
                        <h3><?php echo $title; ?></h3>
                    <?php } ?>
                </div>
                <div class="block-content">                  
                    <ol  class="mini-products-list">
                        <li>
                            <p class="product-name">
                                <a class="product-name" href="<?php echo Mage::getBaseUrl() . $_product->getUrlPath() ?>" title="<?php echo $_product->getName() ?>">
                                    <?php echo $_product->getName() ?>
                                </a>
                            </p>
							<a href="<?php echo Mage::getBaseUrl() . $_product->getUrlPath() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(70); ?>" width="70" height="70" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
							</a>		

                            <div class="product-details">
                                <?php if($_deal->checkDealPrice($_product)){ ?>
                                <?php $_regularPrice = $_taxHelper->getPrice($_product, $_product->getPrice()) ?>
                                <?php $_finalPrice = $_taxHelper->getPrice($_product, $_product->getFinalPrice()) ?>
                                <p class="old-price" >
                                    <span class="regular-price">
                                        <span class="price"><?php echo $_coreHelper->currency($_regularPrice, true, false) ?></span>
                                    </span>
                                </p>
                                <p class="special-price">
                                    <span class="price">
                                        <?php echo $_coreHelper->currency($_finalPrice, true, false) ?>
                                    </span>
                                </p>
                                <?php }else{
                                    $_deal->setMinPriceFollowProductType($_product);
                                ?>
                                <p class="from-price special-price">
                                    <span class="pri-label"><?php echo $this->__('From');?></span>
                                    <span class="price">
                                        <?php echo $_coreHelper->currency($_product->getData('min_price'), true, false) ?>
                                    </span>
                                </p>
                                <?php } ?>
								<button type="button" class="button btn-buynow" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($_product); ?>')"><span><span><?php echo $this->__('Buy now') ?></span></span></button>
                            </div>
                            
                        <?php if ( $_deal->checkDealQtyToShow($_product) && 
                    ( Mage::helper('dailydeal')->getConfigTodayDealShowDetail() || Mage::helper('dailydeal')->getConfigDisplayQuantity())) { ?>
                            
                            
							<?php if (Mage::helper('dailydeal')->getConfigTodayDealShowDetail()) {
								$_deal->processValueDiscountSaveBought(array('model_product' => $_product));
								$_deal_info = $_deal->getData('value_discount_save_bought');
								?>
								<div class="glace_dld_detail">
									<ul>
										<li>
											<span><?php echo Mage::helper('dailydeal')->__('Discount') ?></span>
											<span class="glace_dld_detail_num"><?php echo $_deal_info['discount'] ?></span>
										</li>
										<li>
											<span><?php echo Mage::helper('dailydeal')->__('You Save') ?></span>
											<span class="glace_dld_detail_num"><?php echo $_deal_info['you_save'] ?></span>
										</li>
										<li>
											<span><?php echo Mage::helper('dailydeal')->__('Bought') ?></span>
											<span class="glace_dld_detail_num"><?php echo $_deal_info['bought'] ?></span>
										</li>
									</ul>
								</div>
							<?php } ?>
							
                            
							<?php
							$dealqty = $_deal->getDealQty();
							$soldqty = $_deal->getSoldQty();
							?>
							<div class="dailydeal-qty-box">
								<?php if (Mage::helper('dailydeal')->getConfigDisplayQuantity()) { ?>
									<?php
									if (($dealqty - $soldqty) > 10) {
										echo Mage::helper('dailydeal')->renderDealQtyOnCatalogPage($dealqty - $soldqty);
									} elseif (($dealqty - $soldqty) <= 10 && ($dealqty - $soldqty) > 1) {
										echo Mage::helper('dailydeal')->renderDealQtyOnCatalogPage($dealqty - $soldqty);
									} elseif (($dealqty - $soldqty) == 1) {
										echo Mage::helper('dailydeal')->renderDealQtyOnCatalogPage($dealqty - $soldqty);
									}
									?>
								<?php } ?>
							</div>
                        <?php } ?>
                            
                            
                        </li>
                    </ol>
                    <!-- Countdown Javascript -->
                    <div id="counter" class="counter">
                        <ul class="countdown">	
                            <li class="first">
                                <div class="countdown_num" id="cd_day-<?php echo $_deal->getDailydealId() ?>"></div><div id="cd_day"></div></li>
                            <li>
                                <div class="countdown_num" id="cd_hour-<?php echo $_deal->getDailydealId() ?>"></div><div id="cd_hour"></div></li>
                            <li>
                                <div class="countdown_num" id="cd_min-<?php echo $_deal->getDailydealId() ?>"></div><div id="cd_minute"></div></li>
                            <li class="last">
                                <div class="countdown_num" id="cd_sec-<?php echo $_deal->getDailydealId() ?>"></div><div id="cd_second"></div></li>
                        </ul>
                        <div class="clear"><span>&nbsp;</span></div>
                    </div>
                    <div id="expired" style="display:none;">
                        <?php echo Mage::helper('dailydeal')->__('The deadline has passed.'); ?>
                    </div>
                </div>
            </div>
            <?php $remain_second = strtotime($_deal->getEndDateTime()) - Mage::getModel('core/date')->timestamp(); ?>
            <script type="text/javascript">
                var todaydeal_server_time = { 
                    second : <?php echo $remain_second; ?>,
                    callback : '',
                    
                    id_day  : 'cd_day-' + <?php echo $_deal->getId(); ?>,
                    id_hour  : 'cd_hour-' + <?php echo $_deal->getId(); ?>,
                    id_minute  : 'cd_min-' + <?php echo $_deal->getId(); ?>,
                    id_second  : 'cd_sec-' + <?php echo $_deal->getId(); ?>,
                    
                    label_day : 'cd_day',
                    label_hour : 'cd_hour',
                    label_minute : 'cd_minute',
                    label_second : 'cd_second',
					
					label_day_value : '<?php echo Mage::helper('dailydeal')->__('Day'); ?>',
                    label_hour_value : '<?php echo Mage::helper('dailydeal')->__('Hours'); ?>',
                    label_minute_value : '<?php echo Mage::helper('dailydeal')->__('Mins'); ?>',
                    label_second_value : '<?php echo Mage::helper('dailydeal')->__('Secs'); ?>'
                };
                countDownSecond(todaydeal_server_time);
            </script>     
            <?php break; ?>
        <?php } ?>
    <?php endforeach; ?>
<?php endif; ?>

