<script>
var text_change_product = '<?php echo Mage::helper('dailydeal')->__('Change Product') ?>';
var text_edit_product = '<?php echo Mage::helper('dailydeal')->__('Edit Product') ?>';


var note_qty_configurable = "<?php echo Mage::helper('dailydeal')->__("<span>Qty cannot be set for Configurable Products since it varies for each of it's Associated Products.</span>") ?>";
var note_qty_grouped = "<?php echo Mage::helper('dailydeal')->__("<span>Deal Qty cannot be set for Grouped Products since it varies for each of it's Associated Products.</span>") ?>";
var note_qty_bundle = "<?php echo Mage::helper('dailydeal')->__("<span>Deal Qty cannot be set for Bundle Products since it varies for each of it's Bundle Items.</span>") ?>";
var note_price_grouped = "<?php echo Mage::helper('dailydeal')->__('<span>Deal Price cannot be set for Grouped Products since it depends on the Associated Products.</span>') ?>";
var note_price_bundle = "<?php echo Mage::helper('dailydeal')->__("<span>Deal Price cannot be set for Bundle Products since it varies for each of it's Bundle Items.</span>") ?>";
</script>
