<?php
/**
 *
 * CART2QUOTE CONFIDENTIAL
 * __________________
 *
 *  [2009] - [2015] Cart2Quote B.V.
 *  All Rights Reserved.
 *
 * NOTICE OF LICENSE
 *
 * All information contained herein is, and remains
 * the property of Cart2Quote B.V. and its suppliers,
 * if any.  The intellectual and technical concepts contained
 * herein are proprietary to Cart2Quote B.V.
 * and its suppliers and may be covered by European and Foreign Patents,
 * patents in process, and are protected by trade secret or copyright law.
 * Dissemination of this information or reproduction of this material
 * is strictly forbidden unless prior written permission is obtained
 * from Cart2Quote B.V.
 *
 * @category    Ophirah
 * @package     Qquoteadv
 * @copyright   Copyright (c) 2015 Cart2Quote B.V. (http://www.cart2quote.com)
 * @license     http://www.cart2quote.com/ordering-licenses
 */
?>
<?php
$status = $quoteModel->getData('status');

$btnCreateOrder = $this->getLayout()->createBlock('adminhtml/widget_button');
$btnCreateOrder->setLabel(Mage::helper('sales')->__('Create Order'));
$btnCreateOrder->setClass('save');

$onclick = "if(isCheckRadio()){ $('redirect2neworder').value=1; $('loading-mask').show(); save(); }else{ return false;}";
$btnCreateOrder->setOnclick($onclick);
?>

<?php

$button = $this->getLayout()->createBlock('adminhtml/widget_button');
// Check if quote is allowed for negative profit
$profit = (Mage::getStoreConfig('qquoteadv_quote_configuration/proposal/profit', $quoteModel->getData('store_id')) == 1) ? true : false;
if ($quoteModel->getData('no_profit') == 1 && $profit === false) {
    $button->setLabel($this->__('No profit, increase Price(s)'));
} else {
    $button->setLabel($this->__('Submit Quote'));
}
$button->setClass('save');

if ($status == Ophirah_Qquoteadv_Model_Status::STATUS_ORDERED ||
    $status == Mage::getModel('qquoteadv/status')->getStatusConfirmed() ||
    $status == Ophirah_Qquoteadv_Model_Status::STATUS_PROPOSAL_SAVED ||
    ($quoteModel->getData('no_profit') == 1 && $profit === false)
) {
    $button->setClass('disabled');
    $button->setOnclick("return false;");
} else {
    $onclick = "$('loading-mask').show(); saveAndContinueEdit();";
    $button->setClass();
    $button->setOnclick($onclick);
}
?>

<?php echo $button->_toHtml() . '&nbsp;&nbsp;' . $btnCreateOrder->_toHtml(); ?>

